name: PHP CodeSniffer with Email Notification

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: |
          composer install

      - name: Install PHP CodeSniffer
        run: |
          composer global require "squizlabs/php_codesniffer=*"

      - name: Run PHP CodeSniffer
        id: phpcs
        run: |
          phpcs --standard=.github/phpcs.xml src/ > phpcs-result.log || true
        continue-on-error: true

      - name: Install msmtp
        run: |
          sudo apt-get install msmtp

      - name: Configure msmtp
        run: |
          echo "defaults" > ~/.msmtprc
          echo "auth on" >> ~/.msmtprc
          echo "tls on" >> ~/.msmtprc
          echo "tls_trust_file /etc/ssl/certs/ca-certificates.crt" >> ~/.msmtprc
          echo "account gmail" >> ~/.msmtprc
          echo "host smtp.gmail.com" >> ~/.msmtprc
          echo "port 587" >> ~/.msmtprc
          echo "user ${{ secrets.SMTP_USERNAME }}" >> ~/.msmtprc
          echo "password ${{ secrets.SMTP_PASSWORD }}" >> ~/.msmtprc
          echo "from ${{ secrets.SMTP_USERNAME }}" >> ~/.msmtprc
          echo "account default : gmail" >> ~/.msmtprc
          chmod 600 ~/.msmtprc

      - name: Send Email Notification
        if: failure()  # エラーが発生した場合のみ通知を送信
        run: |
          echo "Subject: PHP CodeSniffer Report" > email.txt
          echo "From: ${{ secrets.SMTP_USERNAME }}" >> email.txt
          echo "To: test+code_sniffer@e2info.com" >> email.txt
          echo "MIME-Version: 1.0" >> email.txt
          echo "Content-Type: text/plain; charset=UTF-8" >> email.txt
          echo "" >> email.txt
          echo "PHP CodeSniffer errors detected in the following files:" >> email.txt
          cat phpcs-result.log >> email.txt
          
          msmtp ${{ secrets.SMTP_USERNAME }} < email.txt
